apiVersion: v1
kind: Service
metadata:
  name: dns-lb-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: dns-lb-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
