apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      # serviceAccountName: default
      # terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: paymentservice
        # ports:
        # - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
