apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-demo
    image: ivorlun/nginxdemo8000:latest
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
    livenessProbe:
      tcpSocket:
        port: 8000
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-nginx-demo
    image: busybox:1.33
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
  - name: app
    emptyDir: {}
